2022-11-17 19:17:57,050 ERROR: Exception on /edit_profile [GET] [in /home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/theodore/Documents/GitHub/python-flask/microblog/app/routes.py", line 133, in edit_profile
    return render_template('edit_profile.html', title='Edit Profile',
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/theodore/Documents/GitHub/python-flask/microblog/app/templates/edit_profile.html", line 8, in template
    {{ wtf.quick_form(form) }}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2022-11-17 19:18:34,780 INFO: Microblog startup [in /home/theodore/Documents/GitHub/python-flask/microblog/app/__init__.py:50]
2022-11-17 19:21:51,717 ERROR: Exception on /register [GET] [in /home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/theodore/Documents/GitHub/python-flask/microblog/app/routes.py", line 94, in register
    return render_template('register.html', title="Register", form=form)
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/theodore/Documents/GitHub/python-flask/microblog/app/templates/register.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/theodore/Documents/GitHub/python-flask/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/theodore/Documents/GitHub/python-flask/microblog/app/templates/base.html", line 48, in block 'content'
    {% block app_content %}{% endblock %}
  File "/home/theodore/Documents/GitHub/python-flask/microblog/app/templates/register.html", line 5, in block 'app_content'
    <h1>{{ _('Register') }}</h1>
  File "/home/theodore/Documents/GitHub/python-flask/microblog/venv/lib/python3.10/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: '_' is undefined
